package view;


//import view.TelaCadastroClient;



public class TelaPrincipalAdm extends javax.swing.JFrame {

   
    public TelaPrincipalAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        painelAreiaTabalho = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mnTelaPricipalAdm = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        itMenuSair = new javax.swing.JMenuItem();
        itMenuLogin = new javax.swing.JMenuItem();
        mnFuncionario = new javax.swing.JMenu();
        itMnCadastroFunc = new javax.swing.JMenuItem();
        itMnPesquisarFun = new javax.swing.JMenuItem();
        itMnAlterarFuncionario = new javax.swing.JMenuItem();
        itMnExcluirCadFuncionario = new javax.swing.JMenuItem();
        itMenuComisoes__ = new javax.swing.JMenuItem();
        mnClientesDoAdm = new javax.swing.JMenu();
        itMnCadCilient = new javax.swing.JMenuItem();
        itMnPesqClient = new javax.swing.JMenuItem();
        itMnCadDeClientes = new javax.swing.JMenuItem();
        itMnExcluirCadCliente = new javax.swing.JMenuItem();
        jMenuCarro = new javax.swing.JMenu();
        cadVeiculo = new javax.swing.JMenuItem();
        pesquisarVeiculo = new javax.swing.JMenuItem();
        altCadVeiculo = new javax.swing.JMenuItem();
        excluirCadVeiculos = new javax.swing.JMenuItem();
        cadVendas = new javax.swing.JMenu();
        itMenuCadVenda = new javax.swing.JMenuItem();
        itMnPesqVendas = new javax.swing.JMenuItem();
        itMnAltVendas = new javax.swing.JMenuItem();
        excluirVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu6.setText("jMenu6");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1800, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(1800, 1000));

        painelAreiaTabalho.setPreferredSize(new java.awt.Dimension(1800, 1000));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/humer2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSample_ByTailorBrands (1) - Copia.png"))); // NOI18N

        painelAreiaTabalho.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelAreiaTabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelAreiaTabalhoLayout = new javax.swing.GroupLayout(painelAreiaTabalho);
        painelAreiaTabalho.setLayout(painelAreiaTabalhoLayout);
        painelAreiaTabalhoLayout.setHorizontalGroup(
            painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addGroup(painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreiaTabalhoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreiaTabalhoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(781, 781, 781))))
        );
        painelAreiaTabalhoLayout.setVerticalGroup(
            painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreiaTabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreiaTabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        mnArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.png"))); // NOI18N
        mnArquivo.setText("Arquivo");
        mnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArquivoActionPerformed(evt);
            }
        });

        itMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_in.png"))); // NOI18N
        itMenuSair.setText("Sair");
        itMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuSairActionPerformed(evt);
            }
        });
        mnArquivo.add(itMenuSair);

        itMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png"))); // NOI18N
        itMenuLogin.setText("Login");
        itMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuLoginActionPerformed(evt);
            }
        });
        mnArquivo.add(itMenuLogin);

        mnTelaPricipalAdm.add(mnArquivo);

        mnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        mnFuncionario.setText("Funcinarios");

        itMnCadastroFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        itMnCadastroFunc.setText("Cadastrar");
        itMnCadastroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadastroFuncActionPerformed(evt);
            }
        });
        mnFuncionario.add(itMnCadastroFunc);

        itMnPesquisarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        itMnPesquisarFun.setText("Pesquisar");
        itMnPesquisarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnPesquisarFunActionPerformed(evt);
            }
        });
        mnFuncionario.add(itMnPesquisarFun);

        itMnAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_edit.png"))); // NOI18N
        itMnAlterarFuncionario.setText("Alterar");
        itMnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAlterarFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(itMnAlterarFuncionario);

        itMnExcluirCadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_delete.png"))); // NOI18N
        itMnExcluirCadFuncionario.setText("Excluir");
        itMnExcluirCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnExcluirCadFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(itMnExcluirCadFuncionario);

        itMenuComisoes__.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-solicitar-dinheiro-18.png"))); // NOI18N
        itMenuComisoes__.setText("Comissoes");
        itMenuComisoes__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuComisoes__ActionPerformed(evt);
            }
        });
        mnFuncionario.add(itMenuComisoes__);

        mnTelaPricipalAdm.add(mnFuncionario);

        mnClientesDoAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        mnClientesDoAdm.setText("Clientes");

        itMnCadCilient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        itMnCadCilient.setText("Cadastrar");
        itMnCadCilient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCilientActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnCadCilient);

        itMnPesqClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        itMnPesqClient.setText("Pesquisar");
        itMnPesqClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnPesqClientActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnPesqClient);

        itMnCadDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alterar-usuário-masculino-18.png"))); // NOI18N
        itMnCadDeClientes.setText("Alterar Cadastro");
        itMnCadDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadDeClientesActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnCadDeClientes);

        itMnExcluirCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir-18.png"))); // NOI18N
        itMnExcluirCadCliente.setText("Excluir Cadastro");
        itMnExcluirCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnExcluirCadClienteActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnExcluirCadCliente);

        mnTelaPricipalAdm.add(mnClientesDoAdm);

        jMenuCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        jMenuCarro.setText("Veiculos");

        cadVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        cadVeiculo.setText("Cadastro");
        cadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(cadVeiculo);

        pesquisarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        pesquisarVeiculo.setText("Pesquisa");
        pesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(pesquisarVeiculo);

        altCadVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlteraCar.png"))); // NOI18N
        altCadVeiculo.setText("Alterar Cadastro");
        altCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altCadVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(altCadVeiculo);

        excluirCadVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir16.png"))); // NOI18N
        excluirCadVeiculos.setText("Excluir Cadastro");
        excluirCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadVeiculosActionPerformed(evt);
            }
        });
        jMenuCarro.add(excluirCadVeiculos);

        mnTelaPricipalAdm.add(jMenuCarro);

        cadVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendaCar-sale2-18.png"))); // NOI18N
        cadVendas.setText("venda");
        cadVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVendasActionPerformed(evt);
            }
        });

        itMenuCadVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-for-sale.png"))); // NOI18N
        itMenuCadVenda.setText("cadastro");
        itMenuCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuCadVendaActionPerformed(evt);
            }
        });
        cadVendas.add(itMenuCadVenda);

        itMnPesqVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        itMnPesqVendas.setText("Pesquisar");
        itMnPesqVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnPesqVendasActionPerformed(evt);
            }
        });
        cadVendas.add(itMnPesqVendas);

        itMnAltVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlteraCar.png"))); // NOI18N
        itMnAltVendas.setText("Alterar Venda");
        itMnAltVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAltVendasActionPerformed(evt);
            }
        });
        cadVendas.add(itMnAltVendas);

        excluirVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir16.png"))); // NOI18N
        excluirVenda.setText("Excluir");
        excluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVendaActionPerformed(evt);
            }
        });
        cadVendas.add(excluirVenda);

        mnTelaPricipalAdm.add(cadVendas);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenu4.setText("Sobre");
        mnTelaPricipalAdm.add(jMenu4);

        setJMenuBar(mnTelaPricipalAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadVendasActionPerformed

    private void itMenuCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuCadVendaActionPerformed
        TelaCadVendas telaCadVen = new TelaCadVendas();
        painelAreiaTabalho.add(telaCadVen);
        telaCadVen.setVisible(true);
    }//GEN-LAST:event_itMenuCadVendaActionPerformed

    private void cadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVeiculoActionPerformed
        TelaCadVeiculo telaCadVe = new TelaCadVeiculo();
        painelAreiaTabalho.add(telaCadVe);
        telaCadVe.setVisible(true);
       
    }//GEN-LAST:event_cadVeiculoActionPerformed

    private void itMnCadCilientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCilientActionPerformed

        TelaCadastroClient telaCadUser = new TelaCadastroClient();
        painelAreiaTabalho.add(telaCadUser);
        telaCadUser.setVisible(true);

    }//GEN-LAST:event_itMnCadCilientActionPerformed

    private void itMnCadastroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadastroFuncActionPerformed
         TelaCadFuncionario telaCadFun = new TelaCadFuncionario();
        painelAreiaTabalho.add(telaCadFun);
        
        telaCadFun.setVisible(true);
        

    }//GEN-LAST:event_itMnCadastroFuncActionPerformed

    private void mnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArquivoActionPerformed

    }//GEN-LAST:event_mnArquivoActionPerformed

    private void itMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuLoginActionPerformed
        TelaLogin telLog = new TelaLogin();
        telLog.setVisible(true);
        dispose();
    }//GEN-LAST:event_itMenuLoginActionPerformed

    private void itMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_itMenuSairActionPerformed

    private void itMnCadDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadDeClientesActionPerformed
        TelaAltClients telaAltClients = new TelaAltClients();
        painelAreiaTabalho.add(telaAltClients);
        telaAltClients.setVisible(true);
    }//GEN-LAST:event_itMnCadDeClientesActionPerformed

    private void itMnAltVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAltVendasActionPerformed
        TelaAltVendas telaAltVendas = new TelaAltVendas();
        painelAreiaTabalho.add(telaAltVendas);
        telaAltVendas.setVisible(true);
    }//GEN-LAST:event_itMnAltVendasActionPerformed

    private void itMnPesquisarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnPesquisarFunActionPerformed
        TelaPesqFuncionario telaPesqFun = new TelaPesqFuncionario();
        painelAreiaTabalho.add(telaPesqFun);
        telaPesqFun.setVisible(true);

    }//GEN-LAST:event_itMnPesquisarFunActionPerformed

    private void itMnPesqClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnPesqClientActionPerformed
        TelaPesquisaClient tel = new TelaPesquisaClient();
        painelAreiaTabalho.add(tel);
        tel.setVisible(true);
    }//GEN-LAST:event_itMnPesqClientActionPerformed

    private void pesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarVeiculoActionPerformed
        TelaPesqVeiculo telaPesqVeiculo = new TelaPesqVeiculo();
        painelAreiaTabalho.add(telaPesqVeiculo);
        telaPesqVeiculo.setVisible(true);
    }//GEN-LAST:event_pesquisarVeiculoActionPerformed

    private void itMnPesqVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnPesqVendasActionPerformed
        TelaPesqVendas telaPesqVendas = new TelaPesqVendas();
        painelAreiaTabalho.add(telaPesqVendas);
        telaPesqVendas.setVisible(true);
    }//GEN-LAST:event_itMnPesqVendasActionPerformed

    private void itMnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAlterarFuncionarioActionPerformed
        TelaAltFuncionario telaAltFuncionario = new TelaAltFuncionario();
        painelAreiaTabalho.add(telaAltFuncionario);
        telaAltFuncionario.setVisible(true);
    }//GEN-LAST:event_itMnAlterarFuncionarioActionPerformed

    private void altCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altCadVeiculoActionPerformed
        TelaAltVeiculo telaAltVeic = new TelaAltVeiculo();
        painelAreiaTabalho.add(telaAltVeic);
        telaAltVeic.setVisible(true);
    }//GEN-LAST:event_altCadVeiculoActionPerformed

    private void itMnExcluirCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnExcluirCadFuncionarioActionPerformed
        
         TelaExcFun telaEx= new TelaExcFun();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
        
        
        
    }//GEN-LAST:event_itMnExcluirCadFuncionarioActionPerformed

    private void itMnExcluirCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnExcluirCadClienteActionPerformed
        TelaExClient telaEx= new TelaExClient();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_itMnExcluirCadClienteActionPerformed

    private void excluirCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadVeiculosActionPerformed
        TelaExVeic telaEx= new TelaExVeic();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_excluirCadVeiculosActionPerformed

    private void excluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVendaActionPerformed
        TelaExVenda telaEx= new TelaExVenda();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
        
        
        
    }//GEN-LAST:event_excluirVendaActionPerformed

    private void itMenuComisoes__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuComisoes__ActionPerformed
        
        TelaComissoes telaEx= new TelaComissoes();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_itMenuComisoes__ActionPerformed

    
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altCadVeiculo;
    private javax.swing.JMenuItem cadVeiculo;
    private javax.swing.JMenu cadVendas;
    private javax.swing.JMenuItem excluirCadVeiculos;
    private javax.swing.JMenuItem excluirVenda;
    private javax.swing.JMenuItem itMenuCadVenda;
    private javax.swing.JMenuItem itMenuComisoes__;
    private javax.swing.JMenuItem itMenuLogin;
    private javax.swing.JMenuItem itMenuSair;
    private javax.swing.JMenuItem itMnAltVendas;
    private javax.swing.JMenuItem itMnAlterarFuncionario;
    private javax.swing.JMenuItem itMnCadCilient;
    private javax.swing.JMenuItem itMnCadDeClientes;
    private javax.swing.JMenuItem itMnCadastroFunc;
    private javax.swing.JMenuItem itMnExcluirCadCliente;
    private javax.swing.JMenuItem itMnExcluirCadFuncionario;
    private javax.swing.JMenuItem itMnPesqClient;
    private javax.swing.JMenuItem itMnPesqVendas;
    private javax.swing.JMenuItem itMnPesquisarFun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuCarro;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnClientesDoAdm;
    private javax.swing.JMenu mnFuncionario;
    private javax.swing.JMenuBar mnTelaPricipalAdm;
    private javax.swing.JDesktopPane painelAreiaTabalho;
    private javax.swing.JMenuItem pesquisarVeiculo;
    // End of variables declaration//GEN-END:variables
}
