/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author guilherme barros
 */
public class TelaPriFun extends javax.swing.JFrame {

    /**
     * Creates new form TelaPriFun
     */
    
    public TelaPriFun() {
        initComponents();
        TelaLogin telLog = new TelaLogin();
        btCpfFun__.setText("COMISSÕES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        painelAreiaTabalho = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btCpfFun__ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mnTelaPricipalAdm = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        itMenuSair = new javax.swing.JMenuItem();
        itMenuLogin = new javax.swing.JMenuItem();
        mnClientesDoAdm = new javax.swing.JMenu();
        itMnCadCilient = new javax.swing.JMenuItem();
        itMnPesqClient = new javax.swing.JMenuItem();
        itMnCadDeClientes = new javax.swing.JMenuItem();
        itMnExcluirCadCliente = new javax.swing.JMenuItem();
        jMenuCarro = new javax.swing.JMenu();
        cadVeiculo = new javax.swing.JMenuItem();
        pesquisarVeiculo = new javax.swing.JMenuItem();
        altCadVeiculo = new javax.swing.JMenuItem();
        excluirCadVeiculos = new javax.swing.JMenuItem();
        cadVendas = new javax.swing.JMenu();
        itMenuCadVenda = new javax.swing.JMenuItem();
        itMnPesqVendas = new javax.swing.JMenuItem();
        itMnAltVendas = new javax.swing.JMenuItem();
        excluirVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1800, 1000));

        jPanel1.setPreferredSize(new java.awt.Dimension(1800, 1000));

        painelAreiaTabalho.setPreferredSize(new java.awt.Dimension(1800, 1000));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carFun.jpg"))); // NOI18N

        btCpfFun__.setBackground(new java.awt.Color(255, 255, 255));
        btCpfFun__.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btCpfFun__.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-solicitar-dinheiro-100.png"))); // NOI18N
        btCpfFun__.setText("jButton1");
        btCpfFun__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCpfFun__ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carFun2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoSample_ByTailorBrands (1) - Copia.png"))); // NOI18N

        painelAreiaTabalho.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelAreiaTabalho.setLayer(btCpfFun__, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelAreiaTabalho.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painelAreiaTabalho.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelAreiaTabalhoLayout = new javax.swing.GroupLayout(painelAreiaTabalho);
        painelAreiaTabalho.setLayout(painelAreiaTabalhoLayout);
        painelAreiaTabalhoLayout.setHorizontalGroup(
            painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                .addGroup(painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCpfFun__, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        painelAreiaTabalhoLayout.setVerticalGroup(
            painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                .addGroup(painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAreiaTabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                            .addComponent(btCpfFun__)
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreiaTabalhoLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelAreiaTabalhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreiaTabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAreiaTabalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        mnArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquivo.png"))); // NOI18N
        mnArquivo.setText("Arquivo");
        mnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnArquivoActionPerformed(evt);
            }
        });

        itMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door_in.png"))); // NOI18N
        itMenuSair.setText("Sair");
        itMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuSairActionPerformed(evt);
            }
        });
        mnArquivo.add(itMenuSair);

        itMenuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png"))); // NOI18N
        itMenuLogin.setText("Login");
        itMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuLoginActionPerformed(evt);
            }
        });
        mnArquivo.add(itMenuLogin);

        mnTelaPricipalAdm.add(mnArquivo);

        mnClientesDoAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        mnClientesDoAdm.setText("Clientes");

        itMnCadCilient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_add.png"))); // NOI18N
        itMnCadCilient.setText("Cadastrar");
        itMnCadCilient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCilientActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnCadCilient);

        itMnPesqClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        itMnPesqClient.setText("Pesquisar");
        itMnPesqClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnPesqClientActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnPesqClient);

        itMnCadDeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alterar-usuário-masculino-18.png"))); // NOI18N
        itMnCadDeClientes.setText("Alterar Cadastro");
        itMnCadDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadDeClientesActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnCadDeClientes);

        itMnExcluirCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir-18.png"))); // NOI18N
        itMnExcluirCadCliente.setText("Excluir Cadastro");
        itMnExcluirCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnExcluirCadClienteActionPerformed(evt);
            }
        });
        mnClientesDoAdm.add(itMnExcluirCadCliente);

        mnTelaPricipalAdm.add(mnClientesDoAdm);

        jMenuCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        jMenuCarro.setText("Veiculos");

        cadVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car_add.png"))); // NOI18N
        cadVeiculo.setText("Cadastro");
        cadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(cadVeiculo);

        pesquisarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        pesquisarVeiculo.setText("Pesquisa");
        pesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(pesquisarVeiculo);

        altCadVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlteraCar.png"))); // NOI18N
        altCadVeiculo.setText("Alterar Cadastro");
        altCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altCadVeiculoActionPerformed(evt);
            }
        });
        jMenuCarro.add(altCadVeiculo);

        excluirCadVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir16.png"))); // NOI18N
        excluirCadVeiculos.setText("Excluir Cadastro");
        excluirCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadVeiculosActionPerformed(evt);
            }
        });
        jMenuCarro.add(excluirCadVeiculos);

        mnTelaPricipalAdm.add(jMenuCarro);

        cadVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendaCar-sale2-18.png"))); // NOI18N
        cadVendas.setText("venda");
        cadVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVendasActionPerformed(evt);
            }
        });

        itMenuCadVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-for-sale.png"))); // NOI18N
        itMenuCadVenda.setText("cadastro");
        itMenuCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMenuCadVendaActionPerformed(evt);
            }
        });
        cadVendas.add(itMenuCadVenda);

        itMnPesqVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        itMnPesqVendas.setText("Pesquisar");
        itMnPesqVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnPesqVendasActionPerformed(evt);
            }
        });
        cadVendas.add(itMnPesqVendas);

        itMnAltVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AlteraCar.png"))); // NOI18N
        itMnAltVendas.setText("Alterar Venda");
        itMnAltVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnAltVendasActionPerformed(evt);
            }
        });
        cadVendas.add(itMnAltVendas);

        excluirVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir16.png"))); // NOI18N
        excluirVenda.setText("Excluir");
        excluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVendaActionPerformed(evt);
            }
        });
        cadVendas.add(excluirVenda);

        mnTelaPricipalAdm.add(cadVendas);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenu4.setText("Sobre");
        mnTelaPricipalAdm.add(jMenu4);

        setJMenuBar(mnTelaPricipalAdm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_itMenuSairActionPerformed

    private void itMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuLoginActionPerformed
        TelaLogin telLog = new TelaLogin();
        telLog.setVisible(true);
        dispose();
    }//GEN-LAST:event_itMenuLoginActionPerformed

    private void mnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnArquivoActionPerformed

    }//GEN-LAST:event_mnArquivoActionPerformed

    private void itMnCadCilientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCilientActionPerformed

        TelaCadastroClient telaCadUser = new TelaCadastroClient();
        painelAreiaTabalho.add(telaCadUser);
        telaCadUser.setVisible(true);
    }//GEN-LAST:event_itMnCadCilientActionPerformed

    private void itMnPesqClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnPesqClientActionPerformed
        TelaPesquisaClient tel = new TelaPesquisaClient();
        painelAreiaTabalho.add(tel);
        tel.setVisible(true);
    }//GEN-LAST:event_itMnPesqClientActionPerformed

    private void itMnCadDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadDeClientesActionPerformed
        TelaAltClients telaAltClients = new TelaAltClients();
        painelAreiaTabalho.add(telaAltClients);
        telaAltClients.setVisible(true);
    }//GEN-LAST:event_itMnCadDeClientesActionPerformed

    private void itMnExcluirCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnExcluirCadClienteActionPerformed
        TelaExClient telaEx= new TelaExClient();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_itMnExcluirCadClienteActionPerformed

    private void cadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVeiculoActionPerformed
        TelaCadVeiculo telaCadVe = new TelaCadVeiculo();
        painelAreiaTabalho.add(telaCadVe);
        telaCadVe.setVisible(true);

    }//GEN-LAST:event_cadVeiculoActionPerformed

    private void pesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarVeiculoActionPerformed
        TelaPesqVeiculo telaPesqVeiculo = new TelaPesqVeiculo();
        painelAreiaTabalho.add(telaPesqVeiculo);
        telaPesqVeiculo.setVisible(true);
    }//GEN-LAST:event_pesquisarVeiculoActionPerformed

    private void altCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altCadVeiculoActionPerformed
        TelaAltVeiculo telaAltVeic = new TelaAltVeiculo();
        painelAreiaTabalho.add(telaAltVeic);
        telaAltVeic.setVisible(true);
    }//GEN-LAST:event_altCadVeiculoActionPerformed

    private void excluirCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadVeiculosActionPerformed
        TelaExVeic telaEx= new TelaExVeic();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_excluirCadVeiculosActionPerformed

    private void itMenuCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMenuCadVendaActionPerformed
        TelaCadVendas telaCadVen = new TelaCadVendas();
        painelAreiaTabalho.add(telaCadVen);
        telaCadVen.setVisible(true);
    }//GEN-LAST:event_itMenuCadVendaActionPerformed

    private void itMnPesqVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnPesqVendasActionPerformed
        TelaPesqVendas telaPesqVendas = new TelaPesqVendas();
        painelAreiaTabalho.add(telaPesqVendas);
        telaPesqVendas.setVisible(true);
    }//GEN-LAST:event_itMnPesqVendasActionPerformed

    private void itMnAltVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnAltVendasActionPerformed
        TelaAltVendas telaAltVendas = new TelaAltVendas();
        painelAreiaTabalho.add(telaAltVendas);
        telaAltVendas.setVisible(true);
    }//GEN-LAST:event_itMnAltVendasActionPerformed

    private void excluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVendaActionPerformed
        TelaExVenda telaEx= new TelaExVenda();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);

    }//GEN-LAST:event_excluirVendaActionPerformed

    private void cadVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadVendasActionPerformed

    private void btCpfFun__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCpfFun__ActionPerformed
        TelaComissoes telaEx= new TelaComissoes();
        painelAreiaTabalho.add(telaEx);
        telaEx.setVisible(true);
    }//GEN-LAST:event_btCpfFun__ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPriFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPriFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPriFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPriFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPriFun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altCadVeiculo;
    private javax.swing.JButton btCpfFun__;
    private javax.swing.JMenuItem cadVeiculo;
    private javax.swing.JMenu cadVendas;
    private javax.swing.JMenuItem excluirCadVeiculos;
    private javax.swing.JMenuItem excluirVenda;
    private javax.swing.JMenuItem itMenuCadVenda;
    private javax.swing.JMenuItem itMenuLogin;
    private javax.swing.JMenuItem itMenuSair;
    private javax.swing.JMenuItem itMnAltVendas;
    private javax.swing.JMenuItem itMnCadCilient;
    private javax.swing.JMenuItem itMnCadDeClientes;
    private javax.swing.JMenuItem itMnExcluirCadCliente;
    private javax.swing.JMenuItem itMnPesqClient;
    private javax.swing.JMenuItem itMnPesqVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuCarro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnClientesDoAdm;
    private javax.swing.JMenuBar mnTelaPricipalAdm;
    private javax.swing.JDesktopPane painelAreiaTabalho;
    private javax.swing.JMenuItem pesquisarVeiculo;
    // End of variables declaration//GEN-END:variables
}
