/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import dao.FuncionarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Vendas;

/**
 *
 * @author guilherme barros
 */
public class TelaComissoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaComissoes
     */
    public TelaComissoes() {
        initComponents();
        DefaultTableModel tabela = (DefaultTableModel) tbComissoes.getModel();
       tbComissoes.setRowSorter(new TableRowSorter(tabela));
    }
    
    
    
    
    private void readJTable(){
        Connection conexão;
        
        DefaultTableModel tabela = (DefaultTableModel) tbComissoes.getModel();
        
        tabela.setNumRows(0);
        
        
        try {
            conexão = new Conexao().getConnection();
            FuncionarioDAO funconarioDao = new FuncionarioDAO(conexão);
            
            for( Vendas vd: funconarioDao.pesquisaComissoes(txtPesqC.getText())){
                
                tabela.addRow(new Object[]{
                    vd.getNomeVendedor(),
                    vd.getCpfFuncionario(),
                    vd.getDataDaVenda(),
                    vd.getComissoes()
                    
                });
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não Encontrado!");
            Logger.getLogger(TelaComissoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbComissoes = new javax.swing.JTable();
        txtPesqC = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btPesq__ = new javax.swing.JButton();

        setClosable(true);

        tbComissoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbComissoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Data da Venda", "Comissões"
            }
        ));
        jScrollPane1.setViewportView(tbComissoes);

        try {
            txtPesqC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CPF Funcionario:");

        btPesq__.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesq__.setText("Pesquisar");
        btPesq__.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesq__ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesqC, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesq__, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btPesq__, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtPesqC))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesq__ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesq__ActionPerformed
        readJTable();
    }//GEN-LAST:event_btPesq__ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesq__;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbComissoes;
    private javax.swing.JFormattedTextField txtPesqC;
    // End of variables declaration//GEN-END:variables
}
